### ISSUE TITLE
NOTHING HAPPEN IN ADAPTER

### ISSUE THREAD

**Issue by asywalulfikri** [armcha/AutoLinkTextView#1]
I implement this code in adapter, but the color not change

 tvContent          = (AutoLinkTextView) itemView.findViewById(R.id.tv_q_content);

            tvContent.addAutoLinkMode(
                    AutoLinkMode.MODE_HASHTAG,
                    AutoLinkMode.MODE_PHONE,
                    AutoLinkMode.MODE_URL,
                    AutoLinkMode.MODE_MENTION,
                    AutoLinkMode.MODE_CUSTOM);
            tvContent.setCustomRegex("\\sAllo\\b");

            tvContent.setHashtagModeColor(ContextCompat.getColor(mContext, R.color.instagram));
            tvContent.setPhoneModeColor(ContextCompat.getColor(mContext, R.color.instagram));
            tvContent.setCustomModeColor(ContextCompat.getColor(mContext, R.color.instagram));
            tvContent.setUrlModeColor(ContextCompat.getColor(mContext, R.color.instagram));
            tvContent.setMentionModeColor(ContextCompat.getColor(mContext, R.color.instagram));
            tvContent.setEmailModeColor(ContextCompat.getColor(mContext, R.color.instagram));
            tvContent.setSelectedStateColor(ContextCompat.getColor(mContext, R.color.instagram));

**Comment by armcha** [comment]
@asywalulfikri did you set ```autoLinkTextView.setAutoLinkText(getString(R.string.long_text));``` ?
