### ISSUE TITLE
[Question] Why made AutoLinkTextView as final class

### ISSUE THREAD

**Issue by aftabsikander** [armcha/AutoLinkTextView#2]
I was wondering why you have made AutoLinkTextView as final class which prevent from extending it for further customization. I wanted to extend your view and provide my own implementation for custom fonts.

For now I have fork your library and made these changes, It would be great if you can remove final in next release.

**Comment by armcha** [comment]
@aftabsikander of course i will remove it, but you can also send me pull request with custom font implementation, to add extra functionality. Thanks!

**Comment by aftabsikander** [comment]
@armcha Sure I will create it as soon as I get free time, Will create a pull request as well for you soon. I was wondering `hash tags and mention tags` should be of small size text then the actual text. so I would update that as well.

Please provide your feedback do you want this feature in my pull request ?

**Comment by armcha** [comment]
@aftabsikander it will be amazing

**Comment by armcha** [comment]
@aftabsikander in new version AutoLinkTextView.java is no longer final class
